'use client'
import GlobalStyle from '../../globalStyles';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <GlobalStyle />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
